# Declarative SQL Data


This notebook allows you to repopulate and/or modify the assignment data, for testing purposes.

This notebook assumes you already have an auth.json file in the current directory, where this notebook is located.

In [ ]:
%load_ext sql

The cells below create a connection string that reads your local auth.json file, returns a string that allows you to connect to the database, and actually connects you to your database.

In [ ]:
import json
def make_conn_str():
    with open("auth.json", "r") as f:
        auth = json.load(f)
        
    username = auth["username"]
    password = auth["password"]
    hostname = "orion-196-39.crc.rice.edu"
    db = username
    
    return f"postgresql://{username}:{password}@{hostname}/{db}"

In [ ]:
conn_str = make_conn_str()

In [ ]:
%sql $conn_str

The following cell deletes the data from all of the data tables.

In [ ]:
%%sql
DELETE FROM flowers CASCADE;

DELETE FROM sightings CASCADE;

DELETE FROM people CASCADE;

DELETE FROM features CASCADE;

Load the **features** data

In [ ]:
%%sql
INSERT INTO features VALUES (0, 'Breckenridge Mountain', 'Summit', 352704, 1183503, 'Breckenridge Mountain', 7510);
INSERT INTO features VALUES (1, 'Brown Peak', 'Summit', 352904, 1182526, 'Piute Peak', 8074);
INSERT INTO features VALUES (2, 'Cold Spring', 'Spring', 352801, 1182349, 'Piute Peak', 7985);
INSERT INTO features VALUES (3, 'Scodie Mountains', 'Range', 353748, 1180455, 'Walker Pass', 7080);
INSERT INTO features VALUES (4, 'Morris Peak', 'Summit', 354125, 1175913, 'Owens Peak', 7208);
INSERT INTO features VALUES (5, 'Steve Spring', 'Spring', 353044, 1182011, 'Woolstalf Creek', 7395);
INSERT INTO features VALUES (6, 'Shirley Peak', 'Summit', 354225, 1183338, 'Alta Sierra', 7087);
INSERT INTO features VALUES (7, 'Piute Peak', 'Summit', 352704, 1182330, 'Piute Peak', 8405);
INSERT INTO features VALUES (8, 'Don Levy Mine', 'Mine', 352451, 1181736, 'Claraville', 7182);
INSERT INTO features VALUES (9, 'Mack Meadow', 'Flat', 353022, 1182045, 'Woolstalf Creek', 7234);
INSERT INTO features VALUES (10, 'Puerto del Suelo', 'Gap', 344937, 1191140, 'Sawmill Mountain', 7680);
INSERT INTO features VALUES (11, 'Gwynnette Mine', 'Mine', 352401, 1181920, 'Claraville', 7214);
INSERT INTO features VALUES (12, 'Frog Meadows Guard Station', 'Locale', 355226, 1183439, 'Tobias Peak', 7631);
INSERT INTO features VALUES (13, 'Liebel Peak', 'Summit', 353026, 1182354, 'Lake Isabella South', 8008);
INSERT INTO features VALUES (14, 'Covington Mountain', 'Summit', 350053, 1182828, 'Tehachapi South', 7851);
INSERT INTO features VALUES (15, 'Camp Alto Campground', 'Locale', 344957, 1191219, 'Sawmill Mountain', 8215);
INSERT INTO features VALUES (16, 'Alaska Flat', 'Flat', 352952, 1182126, 'Claraville', 7513);
INSERT INTO features VALUES (17, 'Brush Mountain', 'Summit', 345304, 1191329, 'Eagle Rest Peak', 7050);
INSERT INTO features VALUES (18, 'Owens Peak', 'Summit', 354418, 1175949, 'Owens Peak', 8435);
INSERT INTO features VALUES (19, 'The George Lodge', 'Locale', 352714, 1182139, 'Claraville', 7146);
INSERT INTO features VALUES (20, 'Tecuya Mountain', 'Summit', 345032, 1185853, 'Frazier Mountain', 7152);
INSERT INTO features VALUES (21, 'Black Mountain', 'Summit', 354430, 1183125, 'Alta Sierra', 7401);
INSERT INTO features VALUES (22, 'Breckenridge Fire Tower', 'Locale', 352703, 1183501, 'Breckenridge Mountain', 7536);
INSERT INTO features VALUES (23, 'Piute Spring', 'Spring', 352649, 1182323, 'Piute Peak', 8038);
INSERT INTO features VALUES (24, 'Tehachapi Mountain', 'Summit', 350248, 1182905, 'Tehachapi South', 7943);
INSERT INTO features VALUES (25, 'Frog Meadows Campground', 'Locale', 355222, 1183436, 'Tobias Peak', 7549);
INSERT INTO features VALUES (26, 'San Emigdio Mountains', 'Range', 345224, 1191044, 'Sawmill Mountain', 7487);
INSERT INTO features VALUES (27, 'Camp Mountain Meadows', 'Locale', 354722, 1183444, 'Tobias Peak', 7103);
INSERT INTO features VALUES (28, 'Campo Alto Campground', 'Locale', 344954, 1191240, 'Sawmill Mountain', 8172);
INSERT INTO features VALUES (29, 'Grouse Meadow', 'Flat', 352434, 1182009, 'Claraville', 7014);
INSERT INTO features VALUES (30, 'McGill Campground', 'Locale', 344856, 1190557, 'Cuddy Valley', 7346);
INSERT INTO features VALUES (31, 'Escapula Peak', 'Summit', 345150, 1190412, 'Cuddy Valley', 7096);
INSERT INTO features VALUES (32, 'San Emigdio Mountain', 'Summit', 345224, 1191044, 'Sawmill Mountain', 7487);
INSERT INTO features VALUES (33, 'Double Mountain', 'Summit', 350200, 1182912, 'Tehachapi South', 7976);
INSERT INTO features VALUES (34, 'Cummings Mountain', 'Summit', 350230, 1183418, 'Cummings Mountain', 7743);
INSERT INTO features VALUES (35, 'King Solomons Ridge', 'Ridge', 352937, 1182539, 'Piute Peak', 7595);
INSERT INTO features VALUES (36, 'Moreland Mill', 'Populated Place', 353026, 1182118, 'Woolstalf Creek', 7743);
INSERT INTO features VALUES (37, 'KERO-TV', 'Tower', 352714, 1183540, 'Breckenridge Mountain', 7477);
INSERT INTO features VALUES (38, 'Inmans', 'Populated Place', 352542, 1182106, 'Claraville', 7408);
INSERT INTO features VALUES (39, 'Burton Mill', 'Locale', 352605, 1182341, 'Piute Peak', 7611);
INSERT INTO features VALUES (40, 'Lone Star Mine', 'Mine', 353024, 1182121, 'Woolstalf Creek', 7736);
INSERT INTO features VALUES (41, 'Grouse Mountain', 'Summit', 344854, 1191059, 'Sawmill Mountain', 8573);
INSERT INTO features VALUES (42, 'Inspiration Point', 'Summit', 353044, 1182127, 'Woolstalf Creek', 7825);
INSERT INTO features VALUES (43, 'Cerro Noroeste', 'Summit', 344951, 1191212, 'Sawmill Mountain', 8284);
INSERT INTO features VALUES (44, 'Water Gap Spring', 'Spring', 354718, 1183510, 'Tobias Peak', 7687);
INSERT INTO features VALUES (45, 'KBAK-TV', 'Tower', 352711, 1183528, 'Breckenridge Mountain', 7533);
INSERT INTO features VALUES (46, 'Brown Meadow', 'Flat', 352859, 1182422, 'Piute Peak', 7349);
INSERT INTO features VALUES (47, 'Bright Star Mine', 'Mine', 353004, 1182136, 'Woolstalf Creek', 7588);
INSERT INTO features VALUES (48, 'Chula Vista Campground', 'Locale', 344849, 1190725, 'Cuddy Valley', 8310);
INSERT INTO features VALUES (49, 'Mount Jenkins', 'Summit', 354233, 1175933, 'Owens Peak', 7864);
INSERT INTO features VALUES (50, 'Sunday Peak', 'Summit', 354657, 1183510, 'Tobias Peak', 8205);
INSERT INTO features VALUES (51, 'Piute Lookout', 'Locale', 352848, 1182133, 'Claraville', 8291);
INSERT INTO features VALUES (52, 'Sawtooth Peak', 'Summit', 354924, 1175956, 'Ninemile Canyon', 7989);
INSERT INTO features VALUES (53, 'Skinner Peak', 'Summit', 353400, 1180736, 'Cane Canyon', 7073);
INSERT INTO features VALUES (54, 'Sorrell Peak', 'Summit', 352503, 1181721, 'Claraville', 7638);

Load the **flowers** data

In [ ]:
%%sql
INSERT INTO flowers VALUES (0, 'Triteleia', 'laxa', 'Ithuriels spear');
INSERT INTO flowers VALUES (1, 'Mimulus', 'primuloides', 'Primrose monkeyflower');
INSERT INTO flowers VALUES (2, 'Viola', 'sheltonii', 'Sheltons violet');
INSERT INTO flowers VALUES (3, 'Polemonium', 'californicum', 'Showy Jacobs ladder');
INSERT INTO flowers VALUES (4, 'Chaenactis', 'douglasii', 'Douglas dustymaiden');
INSERT INTO flowers VALUES (5, 'Castilleja', 'lineariloba', 'Pale owls clover');
INSERT INTO flowers VALUES (6, 'Zigadenus', 'venenosus', 'Death camas');
INSERT INTO flowers VALUES (7, 'Arabis', 'platysperma', 'Broad-seeded rock-cress');
INSERT INTO flowers VALUES (8, 'Calyptridium', 'monospermum', 'One-seeded pussy paws');
INSERT INTO flowers VALUES (9, 'Streptanthus', 'diversifolius', 'Varied-leaved jewelflower');
INSERT INTO flowers VALUES (10, 'Lilium', 'pardalinum', 'Leopard lily');
INSERT INTO flowers VALUES (11, 'Lomatium', 'torreyi', 'Torreys lomatium');
INSERT INTO flowers VALUES (12, 'Penstemon', 'davidsonii', 'Alpine penstemon');
INSERT INTO flowers VALUES (13, 'Lithophragma', 'affine', 'Woodland star');
INSERT INTO flowers VALUES (14, 'Sphenosciadium', 'capitellatum', 'Rangers buttons');
INSERT INTO flowers VALUES (15, 'Geranium', 'molle', 'Doves-foot geranium');
INSERT INTO flowers VALUES (16, 'Gilia', 'mediomontana', 'Globe gilia');
INSERT INTO flowers VALUES (17, 'Dudleya', 'cymosa', 'Canyon dudleya');
INSERT INTO flowers VALUES (18, 'Smilacina', 'racemosa', 'Large false Solomons seal');
INSERT INTO flowers VALUES (19, 'Asarum', 'hartwegii', 'Hartwegs wild ginger');
INSERT INTO flowers VALUES (20, 'Lewisia', 'glandulosa', 'Alpine lewisia');
INSERT INTO flowers VALUES (21, 'Heracleum', 'lanatum', 'Cow parsnip');
INSERT INTO flowers VALUES (22, 'Gilia', 'leptalea', 'Bridges gilia');
INSERT INTO flowers VALUES (23, 'Rumex', 'paucifolia', 'Alpine sheep sorrel');
INSERT INTO flowers VALUES (24, 'Juncus', 'nevadensis', 'Sierra Nevada rush');
INSERT INTO flowers VALUES (25, 'Carex', 'limosa', 'Mud sedge');
INSERT INTO flowers VALUES (26, 'Draperia', 'systyla', 'Draperia');
INSERT INTO flowers VALUES (27, 'Asclepias', 'speciosa', 'Showy milkweed');
INSERT INTO flowers VALUES (28, 'Triphysaria', 'eriantha', 'Butter and eggs');
INSERT INTO flowers VALUES (29, 'Parvisedum', 'pumilum', 'Sierra stonecrop');
INSERT INTO flowers VALUES (30, 'Eriogonum', 'incanum', 'Hoary buckwheat');
INSERT INTO flowers VALUES (31, 'Angelica', 'lineariloba', 'Sierra angelica');
INSERT INTO flowers VALUES (32, 'Sarcodes', 'sanguinea', 'Snow plant');
INSERT INTO flowers VALUES (33, 'Erigeron', 'algidus', 'Sierra daisy');
INSERT INTO flowers VALUES (34, 'Aquilegia', 'pubescens', 'Alpine columbine');
INSERT INTO flowers VALUES (35, 'Arenaria', 'kingii', 'Kings sandwort');
INSERT INTO flowers VALUES (36, 'Eriophyllum', 'lanatum', 'Woolly sunflower');
INSERT INTO flowers VALUES (37, 'Orthilia', 'secunda', 'One-sided wintergreen');
INSERT INTO flowers VALUES (38, 'Phyllodoce', 'breweri', 'Red mountain heather');
INSERT INTO flowers VALUES (39, 'Phlox', 'condensata', 'Condensed phlox');
INSERT INTO flowers VALUES (40, 'Clarkia', 'rhomboidea', 'Diamond clarkia');
INSERT INTO flowers VALUES (41, 'Lupinus', 'polyphyllus', 'Large-leaved lupine');
INSERT INTO flowers VALUES (42, 'Penstemon', 'parvulus', 'Purple penstemon');
INSERT INTO flowers VALUES (43, 'Epilobium', 'angustifolium', 'Fireweed');
INSERT INTO flowers VALUES (44, 'Viola', 'quercetorum', 'Oak violet');
INSERT INTO flowers VALUES (45, 'Senecio', 'hydrophilus', 'Water groundsel');
INSERT INTO flowers VALUES (46, 'Hypericum', 'anagalloides', 'Tinkers penny');
INSERT INTO flowers VALUES (47, 'Mimulus', 'bicolor', 'Yellow-and-white monkeyflower');
INSERT INTO flowers VALUES (48, 'Ligusticum', 'grayi', 'Lovage');
INSERT INTO flowers VALUES (49, 'Fremontodendron', 'californicum', 'California flannelbush');

Load the **people** data

In [ ]:
%%sql
INSERT INTO people VALUES (0, 'Donna');
INSERT INTO people VALUES (1, 'John');
INSERT INTO people VALUES (2, 'Sandra');
INSERT INTO people VALUES (3, 'Robert');
INSERT INTO people VALUES (4, 'Maria');
INSERT INTO people VALUES (5, 'Helen');
INSERT INTO people VALUES (6, 'Brad');
INSERT INTO people VALUES (7, 'James');
INSERT INTO people VALUES (8, 'Pete');
INSERT INTO people VALUES (9, 'Michael');
INSERT INTO people VALUES (10, 'Tim');
INSERT INTO people VALUES (11, 'Jennifer');

Load the **sightings** data

In [ ]:
%%sql
INSERT INTO sightings VALUES (0, 'California flannelbush', 'Jennifer', 'Scodie Mountains', '2006-06-26');
INSERT INTO sightings VALUES (1, 'Pale owls clover', 'Jennifer', 'Frog Meadows Guard Station', '2006-06-01');
INSERT INTO sightings VALUES (2, 'Draperia', 'Jennifer', 'Steve Spring', '2006-09-23');
INSERT INTO sightings VALUES (3, 'Sheltons violet', 'Jennifer', 'Covington Mountain', '2006-06-18');
INSERT INTO sightings VALUES (4, 'One-seeded pussy paws', 'Jennifer', 'Scodie Mountains', '2006-05-29');
INSERT INTO sightings VALUES (5, 'Ithuriels spear', 'Jennifer', 'Scodie Mountains', '2006-06-07');
INSERT INTO sightings VALUES (6, 'Primrose monkeyflower', 'Jennifer', 'Bright Star Mine', '2006-05-19');
INSERT INTO sightings VALUES (7, 'Yellow-and-white monkeyflower', 'Jennifer', 'Piute Peak', '2006-04-18');
INSERT INTO sightings VALUES (8, 'Large false Solomons seal', 'Jennifer', 'Piute Lookout', '2006-06-27');
INSERT INTO sightings VALUES (9, 'Showy Jacobs ladder', 'Jennifer', 'Grouse Meadow', '2006-06-27');
INSERT INTO sightings VALUES (10, 'Douglas dustymaiden', 'Jennifer', 'Burton Mill', '2006-05-29');
INSERT INTO sightings VALUES (11, 'Varied-leaved jewelflower', 'Jennifer', 'Breckenridge Mountain', '2006-05-27');
INSERT INTO sightings VALUES (12, 'Death camas', 'Jennifer', 'Scodie Mountains', '2006-07-09');
INSERT INTO sightings VALUES (13, 'Broad-seeded rock-cress', 'Jennifer', 'Double Mountain', '2006-06-16');
INSERT INTO sightings VALUES (14, 'Diamond clarkia', 'Jennifer', 'Puerto del Suelo', '2006-06-20');
INSERT INTO sightings VALUES (15, 'Leopard lily', 'Jennifer', 'Burton Mill', '2006-07-25');
INSERT INTO sightings VALUES (16, 'Torreys lomatium', 'Jennifer', 'Puerto del Suelo', '2006-09-21');
INSERT INTO sightings VALUES (17, 'Alpine penstemon', 'Jennifer', 'Scodie Mountains', '2006-08-21');
INSERT INTO sightings VALUES (18, 'Alpine sheep sorrel', 'Jennifer', 'Camp Alto Campground', '2006-06-15');
INSERT INTO sightings VALUES (19, 'Woodland star', 'Jennifer', 'Mack Meadow', '2006-08-08');
INSERT INTO sightings VALUES (20, 'Rangers buttons', 'Jennifer', 'Breckenridge Fire Tower', '2006-07-18');
INSERT INTO sightings VALUES (21, 'Doves-foot geranium', 'Jennifer', 'The George Lodge', '2006-05-03');
INSERT INTO sightings VALUES (22, 'Globe gilia', 'Jennifer', 'Puerto del Suelo', '2006-07-23');
INSERT INTO sightings VALUES (23, 'Canyon dudleya', 'Jennifer', 'Moreland Mill', '2006-07-12');
INSERT INTO sightings VALUES (24, 'Red mountain heather', 'Jennifer', 'The George Lodge', '2006-06-20');
INSERT INTO sightings VALUES (25, 'Hartwegs wild ginger', 'Jennifer', 'Piute Lookout', '2006-05-18');
INSERT INTO sightings VALUES (26, 'Snow plant', 'Jennifer', 'Scodie Mountains', '2006-06-09');
INSERT INTO sightings VALUES (27, 'Alpine lewisia', 'Jennifer', 'Piute Lookout', '2006-05-25');
INSERT INTO sightings VALUES (28, 'Cow parsnip', 'Jennifer', 'Liebel Peak', '2006-06-29');
INSERT INTO sightings VALUES (29, 'Sierra daisy', 'Jennifer', 'Double Mountain', '2006-08-12');
INSERT INTO sightings VALUES (30, 'Bridges gilia', 'Jennifer', 'Don Levy Mine', '2006-06-28');
INSERT INTO sightings VALUES (31, 'Sierra Nevada rush', 'Jennifer', 'Gwynnette Mine', '2006-08-10');
INSERT INTO sightings VALUES (32, 'Purple penstemon', 'Jennifer', 'Piute Lookout', '2006-06-30');
INSERT INTO sightings VALUES (33, 'Mud sedge', 'Jennifer', 'Alaska Flat', '2006-05-17');
INSERT INTO sightings VALUES (34, 'Showy milkweed', 'Jennifer', 'Sawtooth Peak', '2006-07-18');
INSERT INTO sightings VALUES (35, 'Kings sandwort', 'Jennifer', 'Sorrell Peak', '2006-06-30');
INSERT INTO sightings VALUES (36, 'Ithuriels spear', 'Jennifer', 'Double Mountain', '2006-08-20');
INSERT INTO sightings VALUES (37, 'One-seeded pussy paws', 'Jennifer', 'Scodie Mountains', '2006-05-07');
INSERT INTO sightings VALUES (38, 'Alpine sheep sorrel', 'Jennifer', 'Scodie Mountains', '2006-09-26');
INSERT INTO sightings VALUES (39, 'Varied-leaved jewelflower', 'Jennifer', 'San Emigdio Mountain', '2006-05-26');
INSERT INTO sightings VALUES (40, 'Primrose monkeyflower', 'Jennifer', 'Puerto del Suelo', '2006-07-11');
INSERT INTO sightings VALUES (41, 'Rangers buttons', 'Jennifer', 'Sorrell Peak', '2006-05-08');
INSERT INTO sightings VALUES (42, 'Leopard lily', 'Jennifer', 'Piute Lookout', '2006-07-27');
INSERT INTO sightings VALUES (43, 'Torreys lomatium', 'Jennifer', 'Alaska Flat', '2006-05-13');
INSERT INTO sightings VALUES (44, 'Tinkers penny', 'Jennifer', 'Campo Alto Campground', '2006-06-30');
INSERT INTO sightings VALUES (45, 'Sheltons violet', 'Jennifer', 'Burton Mill', '2006-07-01');
INSERT INTO sightings VALUES (46, 'Bridges gilia', 'Jennifer', 'Don Levy Mine', '2006-06-15');
INSERT INTO sightings VALUES (47, 'Broad-seeded rock-cress', 'Jennifer', 'Scodie Mountains', '2006-06-26');
INSERT INTO sightings VALUES (48, 'Sierra stonecrop', 'Jennifer', 'Alaska Flat', '2006-07-07');
INSERT INTO sightings VALUES (49, 'Death camas', 'Jennifer', 'Alaska Flat', '2006-06-09');
INSERT INTO sightings VALUES (50, 'Alpine penstemon', 'Jennifer', 'Burton Mill', '2006-05-21');
INSERT INTO sightings VALUES (51, 'Showy Jacobs ladder', 'Jennifer', 'McGill Campground', '2006-06-03');
INSERT INTO sightings VALUES (52, 'Butter and eggs', 'Jennifer', 'Don Levy Mine', '2006-06-29');
INSERT INTO sightings VALUES (53, 'Sierra daisy', 'Jennifer', 'Breckenridge Fire Tower', '2006-05-20');
INSERT INTO sightings VALUES (54, 'Douglas dustymaiden', 'Jennifer', 'Scodie Mountains', '2006-05-19');
INSERT INTO sightings VALUES (55, 'Cow parsnip', 'Jennifer', 'Black Mountain', '2006-07-09');
INSERT INTO sightings VALUES (56, 'Pale owls clover', 'Jennifer', 'Alaska Flat', '2006-07-11');
INSERT INTO sightings VALUES (57, 'Woodland star', 'Jennifer', 'Bright Star Mine', '2006-06-22');
INSERT INTO sightings VALUES (58, 'Cow parsnip', 'Jennifer', 'Puerto del Suelo', '2006-07-12');
INSERT INTO sightings VALUES (59, 'Sierra stonecrop', 'Jennifer', 'Inspiration Point', '2006-06-03');
INSERT INTO sightings VALUES (60, 'Sheltons violet', 'Jennifer', 'Campo Alto Campground', '2006-09-02');
INSERT INTO sightings VALUES (61, 'Primrose monkeyflower', 'Jennifer', 'Mack Meadow', '2006-09-26');
INSERT INTO sightings VALUES (62, 'Broad-seeded rock-cress', 'Jennifer', 'Alaska Flat', '2006-07-11');
INSERT INTO sightings VALUES (63, 'Douglas dustymaiden', 'Jennifer', 'Black Mountain', '2006-06-07');
INSERT INTO sightings VALUES (64, 'Ithuriels spear', 'Jennifer', 'Frog Meadows Campground', '2006-06-28');
INSERT INTO sightings VALUES (65, 'Showy Jacobs ladder', 'Jennifer', 'Don Levy Mine', '2006-07-11');
INSERT INTO sightings VALUES (66, 'Death camas', 'Jennifer', 'Don Levy Mine', '2006-06-24');
INSERT INTO sightings VALUES (67, 'Leopard lily', 'Jennifer', 'Inmans', '2006-06-23');
INSERT INTO sightings VALUES (68, 'Pale owls clover', 'Jennifer', 'Scodie Mountains', '2006-06-02');
INSERT INTO sightings VALUES (69, 'California flannelbush', 'Jennifer', 'Puerto del Suelo', '2006-05-23');
INSERT INTO sightings VALUES (70, 'Red mountain heather', 'Jennifer', 'Piute Lookout', '2006-06-29');
INSERT INTO sightings VALUES (71, 'Woodland star', 'Jennifer', 'Owens Peak', '2006-08-17');
INSERT INTO sightings VALUES (72, 'One-seeded pussy paws', 'Jennifer', 'Tehachapi Mountain', '2006-08-13');
INSERT INTO sightings VALUES (73, 'Alpine columbine', 'Jennifer', 'Bright Star Mine', '2006-07-11');
INSERT INTO sightings VALUES (74, 'Varied-leaved jewelflower', 'Jennifer', 'Piute Lookout', '2006-08-09');
INSERT INTO sightings VALUES (75, 'Torreys lomatium', 'Jennifer', 'King Solomons Ridge', '2006-04-16');
INSERT INTO sightings VALUES (76, 'Tinkers penny', 'Jennifer', 'Scodie Mountains', '2006-06-03');
INSERT INTO sightings VALUES (77, 'Alpine penstemon', 'Jennifer', 'Piute Lookout', '2006-05-26');
INSERT INTO sightings VALUES (78, 'Large-leaved lupine', 'Jennifer', 'Alaska Flat', '2006-06-18');
INSERT INTO sightings VALUES (79, 'Rangers buttons', 'Jennifer', 'Scodie Mountains', '2006-07-21');
INSERT INTO sightings VALUES (80, 'One-sided wintergreen', 'Jennifer', 'Alaska Flat', '2006-06-09');
INSERT INTO sightings VALUES (81, 'Condensed phlox', 'Jennifer', 'Breckenridge Mountain', '2006-08-01');
INSERT INTO sightings VALUES (82, 'Doves-foot geranium', 'Jennifer', 'Skinner Peak', '2006-05-25');
INSERT INTO sightings VALUES (83, 'Globe gilia', 'Jennifer', 'Puerto del Suelo', '2006-06-12');
INSERT INTO sightings VALUES (84, 'Diamond clarkia', 'Jennifer', 'Brush Mountain', '2006-06-16');
INSERT INTO sightings VALUES (85, 'Canyon dudleya', 'Jennifer', 'Steve Spring', '2006-09-28');
INSERT INTO sightings VALUES (86, 'Large false Solomons seal', 'Jennifer', 'Liebel Peak', '2006-06-25');
INSERT INTO sightings VALUES (87, 'Hartwegs wild ginger', 'Jennifer', 'Sorrell Peak', '2006-08-27');
INSERT INTO sightings VALUES (88, 'Alpine lewisia', 'Jennifer', 'Breckenridge Fire Tower', '2006-05-29');
INSERT INTO sightings VALUES (89, 'Sierra Nevada rush', 'Jennifer', 'McGill Campground', '2006-07-29');
INSERT INTO sightings VALUES (90, 'Bridges gilia', 'Jennifer', 'Liebel Peak', '2006-06-18');
INSERT INTO sightings VALUES (91, 'Alpine sheep sorrel', 'Jennifer', 'Scodie Mountains', '2006-08-01');
INSERT INTO sightings VALUES (92, 'Mud sedge', 'Jennifer', 'Brown Peak', '2006-07-18');
INSERT INTO sightings VALUES (93, 'Alpine penstemon', 'Jennifer', 'Frog Meadows Guard Station', '2006-07-22');
INSERT INTO sightings VALUES (94, 'One-seeded pussy paws', 'Jennifer', 'Alaska Flat', '2006-05-14');
INSERT INTO sightings VALUES (95, 'California flannelbush', 'Jennifer', 'Lone Star Mine', '2006-05-09');
INSERT INTO sightings VALUES (96, 'Canyon dudleya', 'Jennifer', 'Breckenridge Mountain', '2006-06-03');
INSERT INTO sightings VALUES (97, 'Broad-seeded rock-cress', 'Jennifer', 'Burton Mill', '2006-05-28');
INSERT INTO sightings VALUES (98, 'Woodland star', 'Jennifer', 'Scodie Mountains', '2006-06-14');
INSERT INTO sightings VALUES (99, 'Rangers buttons', 'Jennifer', 'Bright Star Mine', '2006-07-22');
INSERT INTO sightings VALUES (100, 'Butter and eggs', 'Jennifer', 'Piute Lookout', '2006-05-15');
INSERT INTO sightings VALUES (101, 'Showy Jacobs ladder', 'Jennifer', 'Scodie Mountains', '2006-06-08');
INSERT INTO sightings VALUES (102, 'Ithuriels spear', 'Jennifer', 'Covington Mountain', '2006-05-17');
INSERT INTO sightings VALUES (103, 'Primrose monkeyflower', 'Jennifer', 'Steve Spring', '2006-06-01');
INSERT INTO sightings VALUES (104, 'Sheltons violet', 'Jennifer', 'Piute Lookout', '2006-06-21');
INSERT INTO sightings VALUES (105, 'Douglas dustymaiden', 'Jennifer', 'Grouse Meadow', '2006-05-06');
INSERT INTO sightings VALUES (106, 'Pale owls clover', 'Jennifer', 'Don Levy Mine', '2006-07-15');
INSERT INTO sightings VALUES (107, 'Torreys lomatium', 'Jennifer', 'Liebel Peak', '2006-05-19');
INSERT INTO sightings VALUES (108, 'Death camas', 'Jennifer', 'Piute Lookout', '2006-05-07');
INSERT INTO sightings VALUES (109, 'Alpine sheep sorrel', 'Jennifer', 'Chula Vista Campground', '2006-07-20');
INSERT INTO sightings VALUES (110, 'Varied-leaved jewelflower', 'Jennifer', 'Burton Mill', '2006-07-08');
INSERT INTO sightings VALUES (111, 'Leopard lily', 'Jennifer', 'Scodie Mountains', '2006-07-04');
INSERT INTO sightings VALUES (112, 'Doves-foot geranium', 'Jennifer', 'Tehachapi Mountain', '2006-08-10');
INSERT INTO sightings VALUES (113, 'Globe gilia', 'Jennifer', 'King Solomons Ridge', '2006-06-14');
INSERT INTO sightings VALUES (114, 'Large false Solomons seal', 'Jennifer', 'Breckenridge Fire Tower', '2006-06-10');
INSERT INTO sightings VALUES (115, 'Hartwegs wild ginger', 'Jennifer', 'Cerro Noroeste', '2006-08-04');
INSERT INTO sightings VALUES (116, 'Alpine lewisia', 'Jennifer', 'Puerto del Suelo', '2006-07-25');
INSERT INTO sightings VALUES (117, 'Cow parsnip', 'Jennifer', 'Breckenridge Mountain', '2006-06-01');
INSERT INTO sightings VALUES (118, 'Bridges gilia', 'Jennifer', 'Bright Star Mine', '2006-06-23');
INSERT INTO sightings VALUES (119, 'Purple penstemon', 'Jennifer', 'Scodie Mountains', '2006-09-22');
INSERT INTO sightings VALUES (120, 'Sierra angelica', 'Jennifer', 'Covington Mountain', '2006-08-22');
INSERT INTO sightings VALUES (121, 'Sierra Nevada rush', 'Jennifer', 'Sawtooth Peak', '2006-05-13');
INSERT INTO sightings VALUES (122, 'Mud sedge', 'Jennifer', 'Sorrell Peak', '2006-08-20');
INSERT INTO sightings VALUES (123, 'Draperia', 'Jennifer', 'Mount Jenkins', '2006-07-03');
INSERT INTO sightings VALUES (124, 'Showy milkweed', 'Jennifer', 'Scodie Mountains', '2006-05-12');
INSERT INTO sightings VALUES (125, 'Sierra stonecrop', 'Jennifer', 'King Solomons Ridge', '2006-05-21');
INSERT INTO sightings VALUES (126, 'Hoary buckwheat', 'Jennifer', 'Scodie Mountains', '2006-05-12');
INSERT INTO sightings VALUES (127, 'Ithuriels spear', 'Jennifer', 'Scodie Mountains', '2006-07-03');
INSERT INTO sightings VALUES (128, 'Bridges gilia', 'Maria', 'Chula Vista Campground', '2006-06-26');
INSERT INTO sightings VALUES (129, 'Oak violet', 'Maria', 'Don Levy Mine', '2006-06-01');
INSERT INTO sightings VALUES (130, 'California flannelbush', 'Maria', 'Scodie Mountains', '2006-06-02');
INSERT INTO sightings VALUES (131, 'Condensed phlox', 'Maria', 'Sawtooth Peak', '2006-05-07');
INSERT INTO sightings VALUES (132, 'Douglas dustymaiden', 'Maria', 'Piute Lookout', '2006-07-11');
INSERT INTO sightings VALUES (133, 'Pale owls clover', 'Maria', 'Covington Mountain', '2006-06-28');
INSERT INTO sightings VALUES (134, 'Diamond clarkia', 'Maria', 'Cerro Noroeste', '2006-07-16');
INSERT INTO sightings VALUES (135, 'Primrose monkeyflower', 'Maria', 'Double Mountain', '2006-08-10');
INSERT INTO sightings VALUES (136, 'Sheltons violet', 'Maria', 'Campo Alto Campground', '2006-08-01');
INSERT INTO sightings VALUES (137, 'Showy Jacobs ladder', 'Maria', 'Inmans', '2006-05-02');
INSERT INTO sightings VALUES (138, 'Death camas', 'Maria', 'Scodie Mountains', '2006-06-04');
INSERT INTO sightings VALUES (139, 'Broad-seeded rock-cress', 'Maria', 'Tehachapi Mountain', '2006-05-17');
INSERT INTO sightings VALUES (140, 'Woodland star', 'Maria', 'Cerro Noroeste', '2006-09-12');
INSERT INTO sightings VALUES (141, 'One-seeded pussy paws', 'Maria', 'Double Mountain', '2006-09-14');
INSERT INTO sightings VALUES (142, 'Varied-leaved jewelflower', 'Maria', 'Scodie Mountains', '2006-06-04');
INSERT INTO sightings VALUES (143, 'Cow parsnip', 'Maria', 'Puerto del Suelo', '2006-05-14');
INSERT INTO sightings VALUES (144, 'Leopard lily', 'Maria', 'Chula Vista Campground', '2006-08-14');
INSERT INTO sightings VALUES (145, 'Torreys lomatium', 'Maria', 'Piute Peak', '2006-05-15');
INSERT INTO sightings VALUES (146, 'Alpine penstemon', 'Maria', 'Mack Meadow', '2006-09-13');
INSERT INTO sightings VALUES (147, 'Rangers buttons', 'Maria', 'Moreland Mill', '2006-07-22');
INSERT INTO sightings VALUES (148, 'Doves-foot geranium', 'Maria', 'Alaska Flat', '2006-09-17');
INSERT INTO sightings VALUES (149, 'Globe gilia', 'Maria', 'Liebel Peak', '2006-07-14');
INSERT INTO sightings VALUES (150, 'Canyon dudleya', 'Maria', 'Frog Meadows Campground', '2006-07-06');
INSERT INTO sightings VALUES (151, 'Large false Solomons seal', 'Maria', 'Scodie Mountains', '2006-04-20');
INSERT INTO sightings VALUES (152, 'Hartwegs wild ginger', 'Maria', 'Lone Star Mine', '2006-06-16');
INSERT INTO sightings VALUES (153, 'Alpine lewisia', 'Maria', 'Alaska Flat', '2006-07-16');
INSERT INTO sightings VALUES (154, 'Alpine sheep sorrel', 'Maria', 'Scodie Mountains', '2006-09-23');
INSERT INTO sightings VALUES (155, 'Sierra Nevada rush', 'Maria', 'Alaska Flat', '2006-05-01');
INSERT INTO sightings VALUES (156, 'Mud sedge', 'Maria', 'Piute Peak', '2006-06-26');
INSERT INTO sightings VALUES (157, 'Draperia', 'Maria', 'Scodie Mountains', '2006-05-11');
INSERT INTO sightings VALUES (158, 'Showy milkweed', 'Maria', 'Cerro Noroeste', '2006-06-11');
INSERT INTO sightings VALUES (159, 'Butter and eggs', 'Maria', 'Scodie Mountains', '2006-08-06');
INSERT INTO sightings VALUES (160, 'Snow plant', 'Maria', 'Piute Lookout', '2006-07-10');
INSERT INTO sightings VALUES (161, 'Sierra stonecrop', 'Maria', 'Scodie Mountains', '2006-06-30');
INSERT INTO sightings VALUES (162, 'Sierra daisy', 'Maria', 'Alaska Flat', '2006-05-16');
INSERT INTO sightings VALUES (163, 'Large-leaved lupine', 'Maria', 'Piute Lookout', '2006-07-03');
INSERT INTO sightings VALUES (164, 'Hoary buckwheat', 'Maria', 'Puerto del Suelo', '2006-08-24');
INSERT INTO sightings VALUES (165, 'Sierra angelica', 'Maria', 'Grouse Meadow', '2006-05-19');
INSERT INTO sightings VALUES (166, 'Alpine columbine', 'Maria', 'Chula Vista Campground', '2006-08-28');
INSERT INTO sightings VALUES (167, 'Water groundsel', 'Maria', 'Piute Lookout', '2006-05-19');
INSERT INTO sightings VALUES (168, 'Kings sandwort', 'Maria', 'Don Levy Mine', '2006-06-01');
INSERT INTO sightings VALUES (169, 'Woolly sunflower', 'Maria', 'Don Levy Mine', '2006-07-23');
INSERT INTO sightings VALUES (170, 'One-sided wintergreen', 'Maria', 'Frog Meadows Campground', '2006-06-11');
INSERT INTO sightings VALUES (171, 'Red mountain heather', 'Maria', 'Puerto del Suelo', '2006-08-14');
INSERT INTO sightings VALUES (172, 'Purple penstemon', 'Maria', 'Bright Star Mine', '2006-05-23');
INSERT INTO sightings VALUES (173, 'Fireweed', 'Maria', 'Cerro Noroeste', '2006-05-29');
INSERT INTO sightings VALUES (174, 'Tinkers penny', 'Maria', 'Scodie Mountains', '2006-07-14');
INSERT INTO sightings VALUES (175, 'Yellow-and-white monkeyflower', 'Maria', 'Burton Mill', '2006-06-07');
INSERT INTO sightings VALUES (176, 'Lovage', 'Maria', 'Burton Mill', '2006-05-14');
INSERT INTO sightings VALUES (177, 'Broad-seeded rock-cress', 'Maria', 'Cerro Noroeste', '2006-04-02');
INSERT INTO sightings VALUES (178, 'Primrose monkeyflower', 'Maria', 'Don Levy Mine', '2006-06-12');
INSERT INTO sightings VALUES (179, 'Cow parsnip', 'Maria', 'Scodie Mountains', '2006-06-05');
INSERT INTO sightings VALUES (180, 'Ithuriels spear', 'Maria', 'Burton Mill', '2006-06-26');
INSERT INTO sightings VALUES (181, 'Death camas', 'Maria', 'Inspiration Point', '2006-06-07');
INSERT INTO sightings VALUES (182, 'Sierra stonecrop', 'Maria', 'Inspiration Point', '2006-06-16');
INSERT INTO sightings VALUES (183, 'Sheltons violet', 'Maria', 'KBAK-TV', '2006-07-06');
INSERT INTO sightings VALUES (184, 'Pale owls clover', 'Maria', 'Scodie Mountains', '2006-06-12');
INSERT INTO sightings VALUES (185, 'Showy Jacobs ladder', 'Maria', 'Burton Mill', '2006-08-22');
INSERT INTO sightings VALUES (186, 'Showy milkweed', 'Maria', 'Piute Lookout', '2006-05-30');
INSERT INTO sightings VALUES (187, 'Oak violet', 'Maria', 'Steve Spring', '2006-06-28');
INSERT INTO sightings VALUES (188, 'Douglas dustymaiden', 'Maria', 'Burton Mill', '2006-04-14');
INSERT INTO sightings VALUES (189, 'Canyon dudleya', 'Maria', 'Sawtooth Peak', '2006-05-08');
INSERT INTO sightings VALUES (190, 'One-seeded pussy paws', 'Maria', 'The George Lodge', '2006-06-21');
INSERT INTO sightings VALUES (191, 'Varied-leaved jewelflower', 'Maria', 'Covington Mountain', '2006-04-16');
INSERT INTO sightings VALUES (192, 'Woodland star', 'Maria', 'Liebel Peak', '2006-05-08');
INSERT INTO sightings VALUES (193, 'Leopard lily', 'Maria', 'Scodie Mountains', '2006-06-02');
INSERT INTO sightings VALUES (194, 'Bridges gilia', 'Maria', 'Don Levy Mine', '2006-07-18');
INSERT INTO sightings VALUES (195, 'Torreys lomatium', 'Maria', 'Piute Peak', '2006-07-05');
INSERT INTO sightings VALUES (196, 'Alpine penstemon', 'Maria', 'Inspiration Point', '2006-07-16');
INSERT INTO sightings VALUES (197, 'Rangers buttons', 'Maria', 'Alaska Flat', '2006-08-11');
INSERT INTO sightings VALUES (198, 'Doves-foot geranium', 'Maria', 'Chula Vista Campground', '2006-06-06');
INSERT INTO sightings VALUES (199, 'Butter and eggs', 'Maria', 'Scodie Mountains', '2006-05-20');
INSERT INTO sightings VALUES (200, 'Globe gilia', 'Maria', 'Moreland Mill', '2006-05-01');
INSERT INTO sightings VALUES (201, 'Large false Solomons seal', 'Maria', 'Brown Meadow', '2006-05-10');
INSERT INTO sightings VALUES (202, 'Hoary buckwheat', 'Maria', 'Scodie Mountains', '2006-07-26');
INSERT INTO sightings VALUES (203, 'Sheltons violet', 'Michael', 'Scodie Mountains', '2006-05-26');
INSERT INTO sightings VALUES (204, 'Leopard lily', 'Michael', 'Alaska Flat', '2006-05-04');
INSERT INTO sightings VALUES (205, 'Douglas dustymaiden', 'Michael', 'Bright Star Mine', '2006-08-12');
INSERT INTO sightings VALUES (206, 'Ithuriels spear', 'Michael', 'Scodie Mountains', '2006-09-05');
INSERT INTO sightings VALUES (207, 'Sheltons violet', 'Michael', 'Scodie Mountains', '2006-04-01');
INSERT INTO sightings VALUES (208, 'Primrose monkeyflower', 'Michael', 'Water Gap Spring', '2006-07-07');
INSERT INTO sightings VALUES (209, 'Butter and eggs', 'Michael', 'Burton Mill', '2006-05-21');
INSERT INTO sightings VALUES (210, 'California flannelbush', 'Michael', 'Camp Mountain Meadows', '2006-06-07');
INSERT INTO sightings VALUES (211, 'Ithuriels spear', 'Michael', 'Piute Lookout', '2006-06-25');
INSERT INTO sightings VALUES (212, 'Kings sandwort', 'Michael', 'Morris Peak', '2006-07-08');
INSERT INTO sightings VALUES (213, 'Sheltons violet', 'Michael', 'Owens Peak', '2006-07-16');
INSERT INTO sightings VALUES (214, 'Oak violet', 'Michael', 'Cerro Noroeste', '2006-06-22');
INSERT INTO sightings VALUES (215, 'Canyon dudleya', 'Michael', 'Alaska Flat', '2006-04-13');
INSERT INTO sightings VALUES (216, 'Alpine penstemon', 'Michael', 'Scodie Mountains', '2006-07-25');
INSERT INTO sightings VALUES (217, 'Cow parsnip', 'Michael', 'Lone Star Mine', '2006-08-22');
INSERT INTO sightings VALUES (218, 'Showy Jacobs ladder', 'Michael', 'The George Lodge', '2006-06-12');
INSERT INTO sightings VALUES (219, 'Pale owls clover', 'Michael', 'Scodie Mountains', '2006-06-24');
INSERT INTO sightings VALUES (220, 'Showy milkweed', 'Michael', 'Brown Peak', '2006-05-19');
INSERT INTO sightings VALUES (221, 'Douglas dustymaiden', 'Michael', 'Brown Peak', '2006-05-20');
INSERT INTO sightings VALUES (222, 'Showy Jacobs ladder', 'Michael', 'Scodie Mountains', '2006-05-24');
INSERT INTO sightings VALUES (223, 'Primrose monkeyflower', 'Michael', 'Alaska Flat', '2006-08-20');
INSERT INTO sightings VALUES (224, 'Sheltons violet', 'Michael', 'Double Mountain', '2006-05-27');
INSERT INTO sightings VALUES (225, 'Globe gilia', 'Michael', 'Skinner Peak', '2006-08-20');
INSERT INTO sightings VALUES (226, 'California flannelbush', 'Michael', 'Don Levy Mine', '2006-09-14');
INSERT INTO sightings VALUES (227, 'Ithuriels spear', 'Michael', 'Tecuya Mountain', '2006-05-02');
INSERT INTO sightings VALUES (228, 'Canyon dudleya', 'Michael', 'Frog Meadows Campground', '2006-07-16');
INSERT INTO sightings VALUES (229, 'Sheltons violet', 'Michael', 'Puerto del Suelo', '2006-04-22');
INSERT INTO sightings VALUES (230, 'Varied-leaved jewelflower', 'Michael', 'Sorrell Peak', '2006-06-28');
INSERT INTO sightings VALUES (231, 'Showy milkweed', 'Michael', 'Scodie Mountains', '2006-06-22');
INSERT INTO sightings VALUES (232, 'Sierra stonecrop', 'Michael', 'Alaska Flat', '2006-06-04');
INSERT INTO sightings VALUES (233, 'Ithuriels spear', 'Michael', 'Alaska Flat', '2006-06-28');
INSERT INTO sightings VALUES (234, 'Sheltons violet', 'Michael', 'Piute Lookout', '2006-06-16');
INSERT INTO sightings VALUES (235, 'California flannelbush', 'Michael', 'Burton Mill', '2006-06-24');
INSERT INTO sightings VALUES (236, 'Leopard lily', 'Michael', 'Puerto del Suelo', '2006-06-07');
INSERT INTO sightings VALUES (237, 'Pale owls clover', 'Michael', 'Morris Peak', '2006-06-29');
INSERT INTO sightings VALUES (238, 'Broad-seeded rock-cress', 'Michael', 'McGill Campground', '2006-09-11');
INSERT INTO sightings VALUES (239, 'Leopard lily', 'Michael', 'Owens Peak', '2006-06-05');
INSERT INTO sightings VALUES (240, 'Alpine penstemon', 'Michael', 'Inmans', '2006-08-01');
INSERT INTO sightings VALUES (241, 'Sheltons violet', 'Michael', 'McGill Campground', '2006-05-21');
INSERT INTO sightings VALUES (242, 'Sheltons violet', 'Michael', 'Puerto del Suelo', '2006-04-04');
INSERT INTO sightings VALUES (243, 'Primrose monkeyflower', 'Michael', 'Scodie Mountains', '2006-05-24');
INSERT INTO sightings VALUES (244, 'Showy Jacobs ladder', 'Michael', 'Alaska Flat', '2006-05-08');
INSERT INTO sightings VALUES (245, 'California flannelbush', 'Michael', 'Breckenridge Mountain', '2006-06-22');
INSERT INTO sightings VALUES (246, 'Ithuriels spear', 'Michael', 'Scodie Mountains', '2006-05-21');
INSERT INTO sightings VALUES (247, 'Large-leaved lupine', 'Michael', 'Inspiration Point', '2006-08-23');
INSERT INTO sightings VALUES (248, 'California flannelbush', 'Michael', 'KBAK-TV', '2006-08-20');
INSERT INTO sightings VALUES (249, 'Varied-leaved jewelflower', 'Michael', 'Alaska Flat', '2006-05-10');
INSERT INTO sightings VALUES (250, 'California flannelbush', 'Helen', 'Scodie Mountains', '2006-04-13');
INSERT INTO sightings VALUES (251, 'Woodland star', 'Helen', 'Cold Spring', '2006-08-19');
INSERT INTO sightings VALUES (252, 'Sierra Nevada rush', 'Helen', 'Cold Spring', '2006-08-24');
INSERT INTO sightings VALUES (253, 'Ithuriels spear', 'Helen', 'Cold Spring', '2006-08-03');
INSERT INTO sightings VALUES (254, 'Primrose monkeyflower', 'Helen', 'Scodie Mountains', '2006-06-05');
INSERT INTO sightings VALUES (255, 'Fireweed', 'Helen', 'Liebel Peak', '2006-05-11');
INSERT INTO sightings VALUES (256, 'Varied-leaved jewelflower', 'Helen', 'Scodie Mountains', '2006-06-26');
INSERT INTO sightings VALUES (257, 'Sheltons violet', 'Helen', 'Covington Mountain', '2006-08-29');
INSERT INTO sightings VALUES (258, 'Kings sandwort', 'Helen', 'Alaska Flat', '2006-07-05');
INSERT INTO sightings VALUES (259, 'Alpine penstemon', 'Helen', 'Alaska Flat', '2006-05-30');
INSERT INTO sightings VALUES (260, 'Showy Jacobs ladder', 'Helen', 'Bright Star Mine', '2006-05-25');
INSERT INTO sightings VALUES (261, 'Torreys lomatium', 'Helen', 'Liebel Peak', '2006-06-26');
INSERT INTO sightings VALUES (262, 'Condensed phlox', 'Helen', 'Covington Mountain', '2006-09-19');
INSERT INTO sightings VALUES (263, 'Sheltons violet', 'Helen', 'Alaska Flat', '2006-06-08');
INSERT INTO sightings VALUES (264, 'One-seeded pussy paws', 'Helen', 'Bright Star Mine', '2006-06-28');
INSERT INTO sightings VALUES (265, 'Death camas', 'Helen', 'Liebel Peak', '2006-05-11');
INSERT INTO sightings VALUES (266, 'Primrose monkeyflower', 'Helen', 'Alaska Flat', '2006-06-25');
INSERT INTO sightings VALUES (267, 'Ithuriels spear', 'Helen', 'Don Levy Mine', '2006-05-07');
INSERT INTO sightings VALUES (268, 'California flannelbush', 'Helen', 'Breckenridge Fire Tower', '2006-06-26');
INSERT INTO sightings VALUES (269, 'Kings sandwort', 'Helen', 'Piute Lookout', '2006-06-20');
INSERT INTO sightings VALUES (270, 'Cow parsnip', 'Helen', 'Bright Star Mine', '2006-07-27');
INSERT INTO sightings VALUES (271, 'Showy Jacobs ladder', 'Helen', 'Campo Alto Campground', '2006-07-25');
INSERT INTO sightings VALUES (272, 'Douglas dustymaiden', 'Helen', 'Bright Star Mine', '2006-07-23');
INSERT INTO sightings VALUES (273, 'Showy milkweed', 'Helen', 'Sorrell Peak', '2006-05-13');
INSERT INTO sightings VALUES (274, 'Canyon dudleya', 'Helen', 'Alaska Flat', '2006-07-08');
INSERT INTO sightings VALUES (275, 'Pale owls clover', 'Helen', 'Piute Lookout', '2006-09-18');
INSERT INTO sightings VALUES (276, 'Broad-seeded rock-cress', 'Helen', 'Scodie Mountains', '2006-07-22');
INSERT INTO sightings VALUES (277, 'Varied-leaved jewelflower', 'Helen', 'King Solomons Ridge', '2006-06-05');
INSERT INTO sightings VALUES (278, 'Leopard lily', 'Helen', 'Bright Star Mine', '2006-06-13');
INSERT INTO sightings VALUES (279, 'Torreys lomatium', 'Helen', 'Piute Lookout', '2006-06-06');
INSERT INTO sightings VALUES (280, 'Yellow-and-white monkeyflower', 'Helen', 'Burton Mill', '2006-06-17');
INSERT INTO sightings VALUES (281, 'Alpine penstemon', 'Helen', 'Puerto del Suelo', '2006-06-06');
INSERT INTO sightings VALUES (282, 'Woodland star', 'Helen', 'Water Gap Spring', '2006-06-30');
INSERT INTO sightings VALUES (283, 'Rangers buttons', 'Helen', 'Piute Peak', '2006-05-13');
INSERT INTO sightings VALUES (284, 'Doves-foot geranium', 'Helen', 'Piute Lookout', '2006-06-07');
INSERT INTO sightings VALUES (285, 'Large-leaved lupine', 'Helen', 'Bright Star Mine', '2006-05-30');
INSERT INTO sightings VALUES (286, 'Globe gilia', 'Helen', 'The George Lodge', '2006-05-04');
INSERT INTO sightings VALUES (287, 'Large false Solomons seal', 'Helen', 'Grouse Mountain', '2006-07-21');
INSERT INTO sightings VALUES (288, 'Hartwegs wild ginger', 'Helen', 'Bright Star Mine', '2006-08-05');
INSERT INTO sightings VALUES (289, 'One-sided wintergreen', 'Helen', 'Black Mountain', '2006-06-02');
INSERT INTO sightings VALUES (290, 'Alpine lewisia', 'Helen', 'Bright Star Mine', '2006-07-20');
INSERT INTO sightings VALUES (291, 'Bridges gilia', 'Helen', 'Breckenridge Fire Tower', '2006-06-03');
INSERT INTO sightings VALUES (292, 'Alpine sheep sorrel', 'Helen', 'Scodie Mountains', '2006-05-01');
INSERT INTO sightings VALUES (293, 'Sierra Nevada rush', 'Sandra', 'Piute Lookout', '2006-06-04');
INSERT INTO sightings VALUES (294, 'California flannelbush', 'Sandra', 'Bright Star Mine', '2006-06-02');
INSERT INTO sightings VALUES (295, 'Primrose monkeyflower', 'Sandra', 'Brown Meadow', '2006-06-20');
INSERT INTO sightings VALUES (296, 'Oak violet', 'Sandra', 'Inspiration Point', '2006-06-19');
INSERT INTO sightings VALUES (297, 'Sheltons violet', 'Sandra', 'Piute Lookout', '2006-07-27');
INSERT INTO sightings VALUES (298, 'Rangers buttons', 'Sandra', 'Owens Peak', '2006-06-02');
INSERT INTO sightings VALUES (299, 'Alpine lewisia', 'Sandra', 'Scodie Mountains', '2006-09-09');
INSERT INTO sightings VALUES (300, 'California flannelbush', 'Sandra', 'Bright Star Mine', '2006-08-30');
INSERT INTO sightings VALUES (301, 'Douglas dustymaiden', 'Sandra', 'Inspiration Point', '2006-08-03');
INSERT INTO sightings VALUES (302, 'Primrose monkeyflower', 'Sandra', 'Puerto del Suelo', '2006-06-03');
INSERT INTO sightings VALUES (303, 'Leopard lily', 'Sandra', 'Alaska Flat', '2006-08-13');
INSERT INTO sightings VALUES (304, 'One-seeded pussy paws', 'Sandra', 'Sorrell Peak', '2006-05-23');
INSERT INTO sightings VALUES (305, 'Pale owls clover', 'Sandra', 'Piute Lookout', '2006-05-01');
INSERT INTO sightings VALUES (306, 'Alpine lewisia', 'Sandra', 'Chula Vista Campground', '2006-06-19');
INSERT INTO sightings VALUES (307, 'Douglas dustymaiden', 'Sandra', 'Gwynnette Mine', '2006-05-09');
INSERT INTO sightings VALUES (308, 'Ithuriels spear', 'Sandra', 'Chula Vista Campground', '2006-06-02');
INSERT INTO sightings VALUES (309, 'Primrose monkeyflower', 'Sandra', 'Liebel Peak', '2006-07-27');
INSERT INTO sightings VALUES (310, 'Snow plant', 'Sandra', 'Scodie Mountains', '2006-05-08');
INSERT INTO sightings VALUES (311, 'Ithuriels spear', 'Sandra', 'Scodie Mountains', '2006-07-14');
INSERT INTO sightings VALUES (312, 'Varied-leaved jewelflower', 'Sandra', 'Inspiration Point', '2006-05-08');
INSERT INTO sightings VALUES (313, 'California flannelbush', 'Sandra', 'San Emigdio Mountain', '2006-05-29');
INSERT INTO sightings VALUES (314, 'Primrose monkeyflower', 'Sandra', 'Grouse Mountain', '2006-05-29');
INSERT INTO sightings VALUES (315, 'Canyon dudleya', 'Sandra', 'Brown Meadow', '2006-06-06');
INSERT INTO sightings VALUES (316, 'Alpine lewisia', 'Sandra', 'Covington Mountain', '2006-07-10');
INSERT INTO sightings VALUES (317, 'Ithuriels spear', 'Sandra', 'Puerto del Suelo', '2006-05-29');
INSERT INTO sightings VALUES (318, 'Doves-foot geranium', 'Sandra', 'Breckenridge Fire Tower', '2006-05-23');
INSERT INTO sightings VALUES (319, 'Alpine columbine', 'Donna', 'Chula Vista Campground', '2006-07-03');
INSERT INTO sightings VALUES (320, 'California flannelbush', 'Donna', 'Piute Lookout', '2006-09-01');
INSERT INTO sightings VALUES (321, 'Pale owls clover', 'Donna', 'San Emigdio Mountain', '2006-04-20');
INSERT INTO sightings VALUES (322, 'Ithuriels spear', 'Donna', 'Piute Lookout', '2006-04-30');
INSERT INTO sightings VALUES (323, 'Primrose monkeyflower', 'Donna', 'Breckenridge Mountain', '2006-08-23');
INSERT INTO sightings VALUES (324, 'Kings sandwort', 'Donna', 'Frog Meadows Campground', '2006-06-27');
INSERT INTO sightings VALUES (325, 'Sheltons violet', 'Donna', 'Piute Lookout', '2006-09-24');
INSERT INTO sightings VALUES (326, 'Sierra angelica', 'Donna', 'Puerto del Suelo', '2006-06-16');
INSERT INTO sightings VALUES (327, 'Alpine sheep sorrel', 'Donna', 'Sorrell Peak', '2006-06-16');
INSERT INTO sightings VALUES (328, 'Showy Jacobs ladder', 'Donna', 'Skinner Peak', '2006-07-13');
INSERT INTO sightings VALUES (329, 'Cow parsnip', 'Donna', 'Alaska Flat', '2006-06-21');
INSERT INTO sightings VALUES (330, 'Doves-foot geranium', 'Donna', 'Puerto del Suelo', '2006-06-08');
INSERT INTO sightings VALUES (331, 'Ithuriels spear', 'Donna', 'Piute Lookout', '2006-08-04');
INSERT INTO sightings VALUES (332, 'Globe gilia', 'Donna', 'Scodie Mountains', '2006-09-14');
INSERT INTO sightings VALUES (333, 'Primrose monkeyflower', 'Donna', 'Tecuya Mountain', '2006-07-19');
INSERT INTO sightings VALUES (334, 'California flannelbush', 'Donna', 'Scodie Mountains', '2006-05-21');
INSERT INTO sightings VALUES (335, 'Broad-seeded rock-cress', 'Donna', 'Piute Lookout', '2006-05-16');
INSERT INTO sightings VALUES (336, 'Death camas', 'Donna', 'Don Levy Mine', '2006-08-11');
INSERT INTO sightings VALUES (337, 'Rangers buttons', 'Donna', 'Double Mountain', '2006-07-07');
INSERT INTO sightings VALUES (338, 'Sierra stonecrop', 'Donna', 'Double Mountain', '2006-05-01');
INSERT INTO sightings VALUES (339, 'Sheltons violet', 'Donna', 'Don Levy Mine', '2006-06-18');
INSERT INTO sightings VALUES (340, 'Sierra Nevada rush', 'Donna', 'Sorrell Peak', '2006-05-20');
INSERT INTO sightings VALUES (341, 'Showy Jacobs ladder', 'Donna', 'Scodie Mountains', '2006-07-19');
INSERT INTO sightings VALUES (342, 'Alpine penstemon', 'James', 'Piute Lookout', '2006-05-07');
INSERT INTO sightings VALUES (343, 'Showy Jacobs ladder', 'James', 'Don Levy Mine', '2006-05-24');
INSERT INTO sightings VALUES (344, 'Condensed phlox', 'James', 'Morris Peak', '2006-08-10');
INSERT INTO sightings VALUES (345, 'Ithuriels spear', 'James', 'Camp Mountain Meadows', '2006-05-04');
INSERT INTO sightings VALUES (346, 'Primrose monkeyflower', 'James', 'Cerro Noroeste', '2006-05-30');
INSERT INTO sightings VALUES (347, 'Sheltons violet', 'James', 'Bright Star Mine', '2006-07-26');
INSERT INTO sightings VALUES (348, 'California flannelbush', 'James', 'Frog Meadows Campground', '2006-04-19');
INSERT INTO sightings VALUES (349, 'Douglas dustymaiden', 'James', 'Burton Mill', '2006-06-27');
INSERT INTO sightings VALUES (350, 'One-seeded pussy paws', 'James', 'Don Levy Mine', '2006-06-17');
INSERT INTO sightings VALUES (351, 'Pale owls clover', 'James', 'Scodie Mountains', '2006-06-12');
INSERT INTO sightings VALUES (352, 'Death camas', 'James', 'The George Lodge', '2006-05-30');
INSERT INTO sightings VALUES (353, 'Broad-seeded rock-cress', 'James', 'Piute Spring', '2006-07-13');
INSERT INTO sightings VALUES (354, 'Canyon dudleya', 'James', 'Piute Peak', '2006-05-12');
INSERT INTO sightings VALUES (355, 'Varied-leaved jewelflower', 'James', 'Double Mountain', '2006-08-14');
INSERT INTO sightings VALUES (356, 'Hoary buckwheat', 'James', 'King Solomons Ridge', '2006-05-02');
INSERT INTO sightings VALUES (357, 'Purple penstemon', 'James', 'Puerto del Suelo', '2006-06-02');
INSERT INTO sightings VALUES (358, 'Large false Solomons seal', 'James', 'Owens Peak', '2006-08-28');
INSERT INTO sightings VALUES (359, 'Leopard lily', 'James', 'Don Levy Mine', '2006-05-23');
INSERT INTO sightings VALUES (360, 'Sierra daisy', 'James', 'Cold Spring', '2006-07-07');
INSERT INTO sightings VALUES (361, 'Torreys lomatium', 'James', 'Piute Lookout', '2006-06-06');
INSERT INTO sightings VALUES (362, 'Woodland star', 'James', 'Piute Lookout', '2006-04-24');
INSERT INTO sightings VALUES (363, 'Rangers buttons', 'James', 'Black Mountain', '2006-07-10');
INSERT INTO sightings VALUES (364, 'Death camas', 'John', 'Burton Mill', '2006-05-21');
INSERT INTO sightings VALUES (365, 'California flannelbush', 'John', 'Owens Peak', '2006-08-04');
INSERT INTO sightings VALUES (366, 'Showy Jacobs ladder', 'John', 'Alaska Flat', '2006-05-02');
INSERT INTO sightings VALUES (367, 'Sierra Nevada rush', 'John', 'Scodie Mountains', '2006-05-22');
INSERT INTO sightings VALUES (368, 'Douglas dustymaiden', 'John', 'Owens Peak', '2006-07-12');
INSERT INTO sightings VALUES (369, 'California flannelbush', 'John', 'Piute Lookout', '2006-07-19');
INSERT INTO sightings VALUES (370, 'Primrose monkeyflower', 'John', 'Gwynnette Mine', '2006-05-29');
INSERT INTO sightings VALUES (371, 'Broad-seeded rock-cress', 'John', 'Bright Star Mine', '2006-06-24');
INSERT INTO sightings VALUES (372, 'Ithuriels spear', 'John', 'Owens Peak', '2006-07-22');
INSERT INTO sightings VALUES (373, 'One-seeded pussy paws', 'John', 'Don Levy Mine', '2006-07-08');
INSERT INTO sightings VALUES (374, 'California flannelbush', 'John', 'Piute Lookout', '2006-05-16');
INSERT INTO sightings VALUES (375, 'California flannelbush', 'John', 'Piute Lookout', '2006-08-11');
INSERT INTO sightings VALUES (376, 'Ithuriels spear', 'John', 'Scodie Mountains', '2006-07-17');
INSERT INTO sightings VALUES (377, 'Sierra daisy', 'John', 'Piute Lookout', '2006-08-24');
INSERT INTO sightings VALUES (378, 'Primrose monkeyflower', 'John', 'Mount Jenkins', '2006-06-05');
INSERT INTO sightings VALUES (379, 'Sheltons violet', 'John', 'Don Levy Mine', '2006-09-23');
INSERT INTO sightings VALUES (380, 'California flannelbush', 'Robert', 'Don Levy Mine', '2006-06-04');
INSERT INTO sightings VALUES (381, 'Red mountain heather', 'Robert', 'Alaska Flat', '2006-06-07');
INSERT INTO sightings VALUES (382, 'Torreys lomatium', 'Robert', 'Scodie Mountains', '2006-09-02');
INSERT INTO sightings VALUES (383, 'Death camas', 'Robert', 'Piute Lookout', '2006-05-28');
INSERT INTO sightings VALUES (384, 'Ithuriels spear', 'Robert', 'Alaska Flat', '2006-07-23');
INSERT INTO sightings VALUES (385, 'Hoary buckwheat', 'Robert', 'Black Mountain', '2006-06-18');
INSERT INTO sightings VALUES (386, 'Torreys lomatium', 'Robert', 'Liebel Peak', '2006-05-21');
INSERT INTO sightings VALUES (387, 'Showy Jacobs ladder', 'Robert', 'Owens Peak', '2006-07-21');
INSERT INTO sightings VALUES (388, 'Large-leaved lupine', 'Robert', 'Lone Star Mine', '2006-05-10');
INSERT INTO sightings VALUES (389, 'California flannelbush', 'Robert', 'Cerro Noroeste', '2006-05-01');
INSERT INTO sightings VALUES (390, 'Pale owls clover', 'Robert', 'Breckenridge Fire Tower', '2006-06-19');
INSERT INTO sightings VALUES (391, 'Hartwegs wild ginger', 'Robert', 'Brown Peak', '2006-06-12');
INSERT INTO sightings VALUES (392, 'Varied-leaved jewelflower', 'Robert', 'Piute Lookout', '2006-06-03');
INSERT INTO sightings VALUES (393, 'Sheltons violet', 'Robert', 'Scodie Mountains', '2006-05-13');
INSERT INTO sightings VALUES (394, 'California flannelbush', 'Robert', 'The George Lodge', '2006-07-22');
INSERT INTO sightings VALUES (395, 'Large false Solomons seal', 'Michael', 'Cold Spring', '2006-06-29');
INSERT INTO sightings VALUES (396, 'Sheltons violet', 'Michael', 'Piute Spring', '2006-06-05');
INSERT INTO sightings VALUES (397, 'California flannelbush', 'Michael', 'Scodie Mountains', '2006-07-10');
INSERT INTO sightings VALUES (398, 'Douglas dustymaiden', 'Michael', 'Chula Vista Campground', '2006-07-09');
INSERT INTO sightings VALUES (399, 'Ithuriels spear', 'Michael', 'Grouse Mountain', '2006-07-04');
INSERT INTO sightings VALUES (400, 'Butter and eggs', 'Michael', 'Scodie Mountains', '2006-06-13');
INSERT INTO sightings VALUES (401, 'Death camas', 'Michael', 'Don Levy Mine', '2006-06-04');
INSERT INTO sightings VALUES (402, 'Pale owls clover', 'Michael', 'Sorrell Peak', '2006-06-04');
INSERT INTO sightings VALUES (403, 'Rangers buttons', 'Michael', 'Scodie Mountains', '2006-07-27');
INSERT INTO sightings VALUES (404, 'Draperia', 'Michael', 'Mount Jenkins', '2006-05-08');
INSERT INTO sightings VALUES (405, 'Leopard lily', 'Michael', 'Chula Vista Campground', '2006-05-22');
INSERT INTO sightings VALUES (406, 'California flannelbush', 'Michael', 'Camp Mountain Meadows', '2006-06-28');
INSERT INTO sightings VALUES (407, 'Large false Solomons seal', 'Tim', 'Cold Spring', '2006-06-29');
INSERT INTO sightings VALUES (408, 'Sheltons violet', 'Tim', 'Piute Spring', '2006-06-05');
INSERT INTO sightings VALUES (409, 'California flannelbush', 'Tim', 'Scodie Mountains', '2006-07-10');
INSERT INTO sightings VALUES (410, 'Douglas dustymaiden', 'Tim', 'Chula Vista Campground', '2006-07-09');
INSERT INTO sightings VALUES (411, 'Ithuriels spear', 'Tim', 'Grouse Mountain', '2006-07-04');
INSERT INTO sightings VALUES (412, 'Butter and eggs', 'Tim', 'Scodie Mountains', '2006-06-13');
INSERT INTO sightings VALUES (413, 'Death camas', 'Tim', 'Don Levy Mine', '2006-06-04');
INSERT INTO sightings VALUES (414, 'Pale owls clover', 'Tim', 'Sorrell Peak', '2006-06-04');
INSERT INTO sightings VALUES (415, 'Rangers buttons', 'Tim', 'Scodie Mountains', '2006-07-27');
INSERT INTO sightings VALUES (416, 'Draperia', 'Tim', 'Mount Jenkins', '2006-05-08');
INSERT INTO sightings VALUES (417, 'Sheltons violet', 'Pete', 'Piute Spring', '2006-06-05');
INSERT INTO sightings VALUES (418, 'California flannelbush', 'Pete', 'Scodie Mountains', '2006-07-10');
INSERT INTO sightings VALUES (419, 'Douglas dustymaiden', 'Pete', 'Chula Vista Campground', '2006-07-09');
INSERT INTO sightings VALUES (420, 'Ithuriels spear', 'Pete', 'Grouse Mountain', '2006-07-04');
INSERT INTO sightings VALUES (421, 'Butter and eggs', 'Pete', 'Scodie Mountains', '2006-06-13');
INSERT INTO sightings VALUES (422, 'Death camas', 'Pete', 'Don Levy Mine', '2006-06-04');
INSERT INTO sightings VALUES (423, 'Sheltons violet', 'Brad', 'Piute Spring', '2006-06-05');
INSERT INTO sightings VALUES (424, 'California flannelbush', 'Brad', 'Scodie Mountains', '2006-07-10');
INSERT INTO sightings VALUES (425, 'Douglas dustymaiden', 'Brad', 'Chula Vista Campground', '2006-07-09');

Copyright ©  2019 Rice University, Christopher M Jermaine (cmj4@rice.edu), and Risa B Myers  (rbm2@rice.edu)

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.